package errormessage

var List ErrorMessageList = ErrorMessageList{
    ERR_INVALID_BASIC_AUTH_HEADER.Code:         ERR_INVALID_BASIC_AUTH_HEADER,
    ERR_INVALID_BASIC_AUTH_HEADER_FORMAT.Code:  ERR_INVALID_BASIC_AUTH_HEADER_FORMAT,
    ERR_INVALID_BODY_PARAMETERS.Code:           ERR_INVALID_BODY_PARAMETERS,
    ERR_INVALID_QUERY_PARAMETERS.Code:          ERR_INVALID_QUERY_PARAMETERS,
    ERR_INVALID_FORM_PARAMETERS.Code:           ERR_INVALID_FORM_PARAMETERS,
    ERR_INVALID_BEARER_AUTH_HEADER.Code:        ERR_INVALID_BEARER_AUTH_HEADER,
    ERR_INVALID_BEARER_AUTH_HEADER_FORMAT.Code: ERR_INVALID_BEARER_AUTH_HEADER_FORMAT,
    ERR_INVALID_PASSWORD.Code:                  ERR_INVALID_PASSWORD,
    ERR_USER_NOT_FOUND.Code: ERR_USER_NOT_FOUND,
    ERR_USER_NOT_VERIFIED.Code: ERR_USER_NOT_VERIFIED,
}
